### ISSUE TITLE
Documents

### ISSUE THREAD

**Issue by prudhomm** [numpex/exama#4]
# ExaMA Phase 2

## Proposal

- [ ] [Scientific document](https://docs.google.com/document/d/1hfqw5hm4sBfGVRh6Dqxda4H71u1vXIDB/edit)
- [ ] [Financial annex](https://docs.google.com/spreadsheets/d/1YErnlRpFtLqYbrTer5Wur6-v4xjteSmq/edit?usp=share_link&ouid=109146539207877795266&rtpof=true&sd=true)
- [ ] [Budget](https://docs.google.com/spreadsheets/d/1-IqdJ-nOYUK69B_jLoXCrkS9oxnMo54fElNP1DAZ08U/edit?usp=share_link)

## Work Packages

- [ ] [WP1](https://docs.google.com/document/d/1qoPjq3oJcMKNlwYqs44YBMKM_QB2xxs1f8aG-hE1xbo/edit?usp=share_link)
- [ ] [WP2](https://docs.google.com/document/d/1McuPoHHNwUzU6rfehx87wciWUBbmywBDyu3GSxNFjbw/edit?usp=sharing)
- [ ] [WP3](https://drive.google.com/drive/folders/1AN3bt3MctKSZ7J_wfzIzWwjlxNp4xMif?usp=share_link)
- [ ] [WP4](https://drive.google.com/drive/folders/1whOXKR7lFLnExSro0DFgapz0SIQBI1qX?usp=share_link)
- [ ] [WP5](https://drive.google.com/drive/folders/1lz4J6IdgKwXyJa7h2xV4_-4F9TBnKih-?usp=share_link)
- [ ] [WP6](https://drive.google.com/drive/folders/1miDep-xgbDgmco4m0l98e9BYm6ye85DI?usp=share_link)
- [ ] [WP7](https://drive.google.com/drive/folders/1kAKMWsz3PugQCW55DrzpkM-XEmP9fa-c?usp=share_link)

# ExaMA Phase 1

## Proposal

- [ ] 
- [ ] [PEPR Explo Final Version NumPEx](https://github.com/feelpp/numpex-exama/files/9483221/PEPR-Explo-Final-report.NumPEx.pdf)
